Repository NTHU-SA/NTHU-Data-API, pull requests merged in 2025-03, with the labels that each got.

#168 feat: 改用異步方法來調用 data scraper 的資料
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
  requirements.txt
  src/api/models/buses.py
  src/api/models/courses.py
  src/api/routers/buses.py
  src/api/routers/courses.py
  src/api/schemas/buses.py
  src/utils/__init__.py
  src/utils/data_scraper/__init__.py
  src/utils/data_scraper/api.py
Labels: enhancement

#165 fix(libraries): 修復圖書館新版端點造成的 API 錯誤
  src/api/models/events.py
  src/api/routers/libraries.py
  src/api/schemas/__init__.py
  src/api/schemas/libraries.py
  src/api/schemas/resources.py
  src/utils/scrapers/library_scraper.py
  tests/test_events.py
  tests/test_libraries.py
Labels: bug

#166 feat: remove contact/phones, add departments endpoint
  data/formatted/contacts.json
  scripts/directory/crawler/__init__.py
  scripts/directory/crawler/crawler.py
  scripts/directory/crawler/dept.json
  scripts/directory/crawler/sort_data.py
  scripts/directory/data/dept.json
  scripts/directory/data/phone.json
  scripts/phone_data/original_data/dept.json
  scripts/phone_data/phone_data_node.py
  scripts/phone_data/phone_formatter.py
  src/api/models/contacts.py
  src/api/models/departments.py
  src/api/routers/__init__.py
  src/api/routers/contacts.py
  src/api/routers/departments.py
  tests/test_contacts.py
  tests/test_default.py
  tests/test_departments.py
  tests/test_phones.py
Labels: enhancement

#172 Fix announcements / remove old endpoint
  README.md
  src/api/models/buses.py
  src/api/models/courses.py
  src/api/routers/__init__.py
  src/api/routers/announcements.py
  src/api/routers/bulletins.py
  src/api/routers/buses.py
  src/api/routers/departments.py
  src/api/routers/dining.py
  src/api/routers/energy.py
  src/api/routers/libraries.py
  src/api/routers/scrapers.py
  src/api/schemas/__init__.py
  src/api/schemas/announcements.py
  src/api/schemas/departments.py
  src/api/schemas/libraries.py
  src/api/schemas/resources.py
  src/utils/__init__.py
  src/utils/rpage_scraper.py
  tests/test_bulletins.py
  tests/test_scrapers.py
Labels: bug, refactoring
